DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
dateOfBirth VARCHAR(8) NOT NULL,
phone (10) VARCHAR NOT NULL ,
email VARCHAR(8) NOT NULL,
profession VARCHAR(8) NOT NULL,
creationDate DATE NOT NULL,
departmentId VARCHAR NOT NULL,
);